---
name: Build and Push Docker Image to Google Cloud Platform
on:
  push:
    branches: [ master ]
jobs:
  build-push-to-gcr:
    name: Build and Push to GCP
    runs-on: ubuntu-20.04
    environment: auto_logger
    env:
      IMAGE_NAME: autologger
      PROJECT_ID: autologger
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - id: 'auth'
      uses: 'google-github-actions/auth@v2'
      with:
        credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

    - uses: google-github-actions/setup-gcloud@v2
      with:
        project_id: ${{ env.PROJECT_ID }}

    - name: Build Docker Image
      run: docker build -t $IMAGE_NAME:latest .

#    - name: Automatic Tagging of Releases
#      id: increment-git-tag
#      run: |
#        bash ./scripts/git_update.sh -v major
    - name: Configure Docker Client
      run: |-
        gcloud auth configure-docker europe-southwest1-docker.pkg.dev --quiet
    - name: Push Docker Image to Artifact Registry
      env:
        #GIT_TAG: ${{ steps.increment-git-tag.outputs.git-tag }}
        GIT_TAG: v1.2.0
      run: |-
        docker tag $IMAGE_NAME:latest europe-southwest1-docker.pkg.dev/$PROJECT_ID/images-rep/$IMAGE_NAME:latest
        docker tag $IMAGE_NAME:latest europe-southwest1-docker.pkg.dev/$PROJECT_ID/images-rep/$IMAGE_NAME:$GIT_TAG
        docker push europe-southwest1-docker.pkg.dev/$PROJECT_ID/images-rep/$IMAGE_NAME:latest
        docker push europe-southwest1-docker.pkg.dev/$PROJECT_ID/images-rep/$IMAGE_NAME:$GIT_TAG
  